# Generated by Django 2.2 on 2020-10-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('1', 'Running'), ('2', 'Weight Training'), ('3', 'HIIT'), ('4', 'Yoga'), ('5', 'Pilates'), ('6', 'Crossfit'), ('7', 'Dance Fitness'), ('8', 'Cycling'), ('9', 'Aerobics'), ('10', 'Swimming')], max_length=50)),
                ('new_exercise', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('1', '1-2 Times Per Week'), ('2', '2-3 Times Per Week'), ('3', '3-4 Times Per Week'), ('4', '4-5 Times Per Week'), ('5', '5+ Times Per Week')], max_length=50)),
                ('time_day', models.CharField(choices=[('1', 'Morning'), ('2', 'Afternoon'), ('3', 'Evening'), ('4', 'Flexible')], max_length=50)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Prefer Not to Say')], max_length=50)),
                ('location_city', models.CharField(max_length=50)),
                ('location_state', models.CharField(max_length=2)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_profile', to='gym_buddy.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_to', to='gym_buddy.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_from', to='gym_buddy.User')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profiles', models.ManyToManyField(related_name='fav_exercises', to='gym_buddy.Profile')),
            ],
        ),
    ]
