# Generated by Django 2.2 on 2020-10-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='workout_type',
            field=models.CharField(choices=[('1', 'Running'), ('2', 'Weight Training'), ('3', 'HIIT'), ('4', 'Yoga'), ('5', 'Pilates'), ('6', 'Crossfit'), ('7', 'Dance Fitness'), ('8', 'Cycling'), ('9', 'Aerobics'), ('10', 'Swimming')], max_length=255),
        ),
    ]
