# Generated by Django 2.2 on 2020-10-08 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0002_auto_20201007_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='faved_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='workout_user', to='gym_buddy.User'),
            preserve_default=False,
        ),
    ]
