# Generated by Django 2.2 on 2020-10-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0004_remove_exercise_faved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(),
        ),
    ]
