# Generated by Django 2.2 on 2020-10-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0005_auto_20201019_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
