# Generated by Django 2.2 on 2020-10-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0006_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
