# Generated by Django 2.2 on 2020-11-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0009_forum_comment_forum_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_message',
            name='message_subjext',
            field=models.CharField(default='', max_length=75),
            preserve_default=False,
        ),
    ]
