# Generated by Django 2.2 on 2020-11-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0010_forum_message_message_subjext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_message',
            old_name='message_subjext',
            new_name='message_subject',
        ),
    ]
