# Generated by Django 2.2 on 2020-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0012_auto_20201109_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location_state',
            field=models.CharField(max_length=45),
        ),
    ]
