# Generated by Django 2.2 on 2020-11-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0014_auto_20201109_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_comment',
            old_name='wall_message',
            new_name='forum_message',
        ),
    ]
