# Generated by Django 2.2 on 2020-11-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_buddy', '0015_auto_20201109_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum_comment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='forum_message',
            old_name='created_at',
            new_name='time_stamp',
        ),
        migrations.CreateModel(
            name='Comment_Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_comment', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forum_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='gym_buddy.Forum_Comment')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_replies', to='gym_buddy.User')),
            ],
        ),
    ]
